-- Blyth Cabin QITP v2 reseed. Replaces the project's sections with the 10-section
-- structure from 'Durata Cabin QITP - sections.xlsx' (responsible parties, item
-- objects with hold + photo mode). Deleting the old sections cascades their
-- records + photos; the 140 cabins (and their QR tokens) are untouched.
--
-- Attaches to the EXISTING Blyth project, resolved by code '26004' at apply time
-- — it does NOT create one. Every statement is written as `INSERT ... SELECT ...
-- FROM projects WHERE code='26004'` (the form 0086 uses) so it inserts nothing on
-- a database where 26004 was never raised, instead of inserting a NULL
-- project_id and tripping the NOT NULL constraint. That keeps the migration
-- chain replayable from scratch on a fresh/local DB.
DELETE FROM qitp_sections WHERE project_id = (SELECT id FROM projects WHERE code='26004');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 1,'Pre-Strip Survey & Isolation','HOLD','["Durata"]','[{"text": "Cabin ID confirmed and matches register / drawing", "hold": false, "photo": "none"}, {"text": "Photographic condition survey of all elevations complete", "hold": false, "photo": "optional"}, {"text": "Existing defects / damage logged with photos", "hold": false, "photo": "none"}, {"text": "Power & lighting isolation by Durata confirmed", "hold": false, "photo": "none"}, {"text": "Access (MEWP/scaffold) in place; task RAMS briefed to operatives", "hold": false, "photo": "none"}, {"text": "Joint pre-strip condition survey agreed with Durata", "hold": true, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 2,'Internal Strip Out',NULL,'["Durata"]','[{"text": "Strip-out loose containment and materials", "hold": false, "photo": "optional"}, {"text": "Any materials that are to remain in the cabin, have been moved to the centre and fixed down with bands and screws", "hold": false, "photo": "none"}, {"text": "Fixings retained, bagged and labelled to cabin, removed from cabin or fixed down", "hold": false, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 3,'External Strip Out',NULL,'["Durata", "PGP"]','[{"text": "Flashings removed and labelled to this cabin ID", "hold": false, "photo": "optional"}, {"text": "Gutters removed and set aside / labelled", "hold": false, "photo": "none"}, {"text": "Downpipes removed", "hold": false, "photo": "none"}, {"text": "Fixings retained, bagged and labelled to cabin", "hold": false, "photo": "none"}, {"text": "Exposed roof / openings made weathertight after strip", "hold": false, "photo": "none"}, {"text": "No damage to cabin envelope (photo evidence)", "hold": false, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 4,'Pre-Bolt Release Actions',NULL,'["Durata"]','[{"text": "Ratchet straps in place away from the leading edge to act as a hand rail", "hold": false, "photo": "none"}, {"text": "Lifting points checked; certified lift plan in place", "hold": false, "photo": "none"}, {"text": "All 4 lifting points connected to crane", "hold": false, "photo": "none"}, {"text": "Banksman in place", "hold": false, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 5,'Cabin Bolt Release','HOLD','["Durata"]','[{"text": "External elevation top left bolt removed", "hold": false, "photo": "none"}, {"text": "External elevation top right bolt removed", "hold": false, "photo": "none"}, {"text": "External elevation bottom left bolt removed", "hold": false, "photo": "none"}, {"text": "External elevation bottem right bolt removed", "hold": false, "photo": "none"}, {"text": "Internal elevation top left bolt removed", "hold": false, "photo": "none"}, {"text": "Internal elevation top right bolt removed", "hold": false, "photo": "none"}, {"text": "Internal elevation bottom left bolt removed", "hold": false, "photo": "none"}, {"text": "Internal elevation bottem right bolt removed", "hold": false, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 6,'Ready to Lift','HOLD','["Durata", "Bradden"]','[{"text": "Ready to lift", "hold": true, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 7,'Wrap, Lift & Transport',NULL,'["Durata", "Bradden"]','[{"text": "Lift completed without damage", "hold": false, "photo": "none"}, {"text": "Transport to laydown / storage complete", "hold": false, "photo": "none"}, {"text": "Condition on arrival recorded (photo)", "hold": false, "photo": "optional"}, {"text": "Cabin wrapped", "hold": false, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 8,'Storage / Receipt','HOLD','["Durata"]','[{"text": "Storage location / bay recorded against cabin ID", "hold": false, "photo": "none"}, {"text": "Set down level and packed / supported correctly", "hold": false, "photo": "none"}, {"text": "Weather protection in place", "hold": false, "photo": "optional"}, {"text": "Condition while stored checked (no ingress / damage)", "hold": false, "photo": "none"}, {"text": "Ready-to-reinstall confirmation before lift back", "hold": true, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 9,'Re-site & Reinstall','HOLD','["Durata"]','[{"text": "Foundations / base ready and level checked (critical gate)", "hold": true, "photo": "optional"}, {"text": "Cabin positioned and levelled to setting-out", "hold": false, "photo": "optional"}, {"text": "Links / inter-cabin connections made", "hold": false, "photo": "optional"}, {"text": "Flashings reinstalled (correct cabin set)", "hold": false, "photo": "optional"}, {"text": "Gutters reinstalled and falls checked", "hold": false, "photo": "optional"}, {"text": "Downpipes reinstalled and connected to drainage", "hold": false, "photo": "optional"}, {"text": "Weathertightness / water test completed", "hold": false, "photo": "optional"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) SELECT id, 10,'Final Inspection & Handover','HOLD','["Durata"]','[{"text": "Snagging complete; defects closed out", "hold": false, "photo": "optional"}, {"text": "As-built / completion photos taken", "hold": false, "photo": "optional"}, {"text": "QA records for this cabin complete", "hold": false, "photo": "none"}, {"text": "Client (Durata) sign-off obtained", "hold": true, "photo": "none"}, {"text": "Handover accepted", "hold": false, "photo": "none"}]','2026-06-26T12:00:00.000Z' FROM projects WHERE code='26004';
