-- 0066: Blyth (26004) Cabin QITP — Rev 1 sections + re-sequenced dismantle programme.
-- Sections re-issued from 'PGP Cabin QITP - sections Rev 1.xlsx'; dismantle days
-- re-sequenced to the optimised ~5-lifts/day plan (Dismantle_Sequence deck).
-- CABIN ROWS ARE NOT TOUCHED EXCEPT dismantle_day — the QR `token` of every cabin
-- is preserved (printed & attached on site). Reinstall is handled separately.

-- Clear the few setup/test inspection rows so the re-structured sections start clean
-- (old records reference the previous section ids; section 5 went 8 items -> 1).
DELETE FROM qitp_photos   WHERE cabin_id IN (SELECT id FROM qitp_cabins WHERE project_id = (SELECT id FROM projects WHERE code='26004'));
DELETE FROM qitp_signoffs WHERE cabin_id IN (SELECT id FROM qitp_cabins WHERE project_id = (SELECT id FROM projects WHERE code='26004'));
DELETE FROM qitp_records  WHERE cabin_id IN (SELECT id FROM qitp_cabins WHERE project_id = (SELECT id FROM projects WHERE code='26004'));
DELETE FROM qitp_sections WHERE project_id = (SELECT id FROM projects WHERE code='26004');

INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),1,'Pre-Strip Survey & Isolation','HOLD','["Durata"]','[{"text": "Cabin ID confirmed and matches register / drawing", "hold": false, "photo": "none"}, {"text": "Photographic condition survey of all elevations complete", "hold": false, "photo": "optional"}, {"text": "Existing defects / damage logged with photos", "hold": false, "photo": "optional"}, {"text": "Power & lighting isolation by Durata confirmed", "hold": false, "photo": "none"}, {"text": "Access (MEWP/scaffold) in place; task RAMS briefed to operatives", "hold": false, "photo": "none"}, {"text": "HOLD: Joint pre-strip condition survey agreed with Durata", "hold": true, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),2,'Internal Strip Out',NULL,'["Durata"]','[{"text": "Strip-out loose containment and materials", "hold": false, "photo": "none"}, {"text": "Any materials that are to remain in the cabin, have been moved to the centre and fixed down with bands and screws", "hold": false, "photo": "none"}, {"text": "Fixings retained, bagged and labelled to cabin, removed from cabin or fixed down", "hold": false, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),3,'External Strip Out',NULL,'["Durata", "PGP"]','[{"text": "Flashings removed and labelled to this cabin ID", "hold": false, "photo": "none"}, {"text": "Gutters removed and set aside / labelled", "hold": false, "photo": "none"}, {"text": "Downpipes removed", "hold": false, "photo": "none"}, {"text": "Fixings retained, bagged and labelled to cabin", "hold": false, "photo": "none"}, {"text": "Exposed roof / openings made weathertight after strip", "hold": false, "photo": "none"}, {"text": "No damage to cabin envelope (photo evidence)", "hold": false, "photo": "optional"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),4,'Pre-Bolt Release Actions',NULL,'["Durata", "Bradden"]','[{"text": "Ratchet straps in place away from the leading edge to act as a hand rail", "hold": false, "photo": "none"}, {"text": "Lifting points checked; certified lift plan in place", "hold": false, "photo": "none"}, {"text": "Pre lift checks complete", "hold": false, "photo": "none"}, {"text": "All 4 lifting points connected to crane", "hold": false, "photo": "none"}, {"text": "Banksman in place", "hold": false, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),5,'Bolt Release','HOLD','["Durata"]','[{"text": "All bolts released", "hold": false, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),6,'Ready to Lift','HOLD','["Durata", "Bradden"]','[{"text": "Ready to lift", "hold": true, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),7,'Wrap, Lift & Transport',NULL,'["Durata", "Bradden", "Rhino Wrap"]','[{"text": "Lift completed without damage", "hold": false, "photo": "none"}, {"text": "Transport to laydown / storage complete", "hold": false, "photo": "none"}, {"text": "Condition on arrival recorded (photo)", "hold": false, "photo": "optional"}, {"text": "Cabin wrapped", "hold": false, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),8,'Storage / Receipt','HOLD','["Durata", "Rhino Wrap"]','[{"text": "Storage location / bay recorded against cabin ID", "hold": false, "photo": "none"}, {"text": "Set down level and packed / supported correctly", "hold": false, "photo": "none"}, {"text": "Weather protection in place", "hold": false, "photo": "none"}, {"text": "Condition while stored checked (no ingress / damage)", "hold": false, "photo": "none"}, {"text": "HOLD: Ready-to-reinstall confirmation before lift back", "hold": true, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),9,'Re-site & Reinstall','HOLD','["Durata"]','[{"text": "HOLD: Foundations / base ready and level checked (critical gate)", "hold": true, "photo": "none"}, {"text": "Cabin positioned and levelled to setting-out", "hold": false, "photo": "none"}, {"text": "Links / inter-cabin connections made", "hold": false, "photo": "none"}, {"text": "Flashings reinstalled (correct cabin set)", "hold": false, "photo": "none"}, {"text": "Gutters reinstalled and falls checked", "hold": false, "photo": "none"}, {"text": "Downpipes reinstalled and connected to drainage", "hold": false, "photo": "none"}, {"text": "Weathertightness / water test completed", "hold": false, "photo": "none"}]','2026-06-30T00:00:00.000Z');
INSERT INTO qitp_sections (project_id, seq, title, point_type, responsible, items, created_at) VALUES ((SELECT id FROM projects WHERE code='26004'),10,'Final Inspection & Handover','HOLD','["Durata"]','[{"text": "Snagging complete; defects closed out", "hold": false, "photo": "none"}, {"text": "As-built / completion photos taken", "hold": false, "photo": "optional"}, {"text": "QA records for this cabin complete", "hold": false, "photo": "none"}, {"text": "HOLD: Client (Durata) sign-off obtained", "hold": true, "photo": "none"}, {"text": "Handover accepted", "hold": false, "photo": "none"}]','2026-06-30T00:00:00.000Z');

-- Re-sequenced dismantle days (continuous: Top/Middle 1-19, Ground 20-29).
UPDATE qitp_cabins SET dismantle_day = 29 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G1';
UPDATE qitp_cabins SET dismantle_day = 29 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G2';
UPDATE qitp_cabins SET dismantle_day = 28 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G3';
UPDATE qitp_cabins SET dismantle_day = 28 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G4';
UPDATE qitp_cabins SET dismantle_day = 28 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G5';
UPDATE qitp_cabins SET dismantle_day = 27 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G6';
UPDATE qitp_cabins SET dismantle_day = 27 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G7';
UPDATE qitp_cabins SET dismantle_day = 26 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G8';
UPDATE qitp_cabins SET dismantle_day = 26 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G9';
UPDATE qitp_cabins SET dismantle_day = 25 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G10';
UPDATE qitp_cabins SET dismantle_day = 25 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G11';
UPDATE qitp_cabins SET dismantle_day = 25 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G12';
UPDATE qitp_cabins SET dismantle_day = 24 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G13';
UPDATE qitp_cabins SET dismantle_day = 24 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G14';
UPDATE qitp_cabins SET dismantle_day = 23 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G15';
UPDATE qitp_cabins SET dismantle_day = 23 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G16';
UPDATE qitp_cabins SET dismantle_day = 23 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G17';
UPDATE qitp_cabins SET dismantle_day = 22 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G18';
UPDATE qitp_cabins SET dismantle_day = 22 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G19';
UPDATE qitp_cabins SET dismantle_day = 21 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G20';
UPDATE qitp_cabins SET dismantle_day = 21 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G21';
UPDATE qitp_cabins SET dismantle_day = 20 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G22';
UPDATE qitp_cabins SET dismantle_day = 20 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G23';
UPDATE qitp_cabins SET dismantle_day = 20 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G24';
UPDATE qitp_cabins SET dismantle_day = 29 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G25';
UPDATE qitp_cabins SET dismantle_day = 29 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G26';
UPDATE qitp_cabins SET dismantle_day = 29 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G27';
UPDATE qitp_cabins SET dismantle_day = 28 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G28';
UPDATE qitp_cabins SET dismantle_day = 28 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G29';
UPDATE qitp_cabins SET dismantle_day = 27 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G30';
UPDATE qitp_cabins SET dismantle_day = 27 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G31';
UPDATE qitp_cabins SET dismantle_day = 26 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G32';
UPDATE qitp_cabins SET dismantle_day = 26 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G33';
UPDATE qitp_cabins SET dismantle_day = 26 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G34';
UPDATE qitp_cabins SET dismantle_day = 25 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G35';
UPDATE qitp_cabins SET dismantle_day = 25 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G36';
UPDATE qitp_cabins SET dismantle_day = 24 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G37';
UPDATE qitp_cabins SET dismantle_day = 24 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G38';
UPDATE qitp_cabins SET dismantle_day = 24 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G39';
UPDATE qitp_cabins SET dismantle_day = 23 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G40';
UPDATE qitp_cabins SET dismantle_day = 23 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G41';
UPDATE qitp_cabins SET dismantle_day = 22 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G42';
UPDATE qitp_cabins SET dismantle_day = 22 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G43';
UPDATE qitp_cabins SET dismantle_day = 21 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G44';
UPDATE qitp_cabins SET dismantle_day = 21 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G45';
UPDATE qitp_cabins SET dismantle_day = 21 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G46';
UPDATE qitp_cabins SET dismantle_day = 20 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G47';
UPDATE qitp_cabins SET dismantle_day = 20 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'G48';
UPDATE qitp_cabins SET dismantle_day = 19 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M1';
UPDATE qitp_cabins SET dismantle_day = 19 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M2';
UPDATE qitp_cabins SET dismantle_day = 18 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M3';
UPDATE qitp_cabins SET dismantle_day = 18 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M4';
UPDATE qitp_cabins SET dismantle_day = 18 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M5';
UPDATE qitp_cabins SET dismantle_day = 17 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M6';
UPDATE qitp_cabins SET dismantle_day = 16 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M7';
UPDATE qitp_cabins SET dismantle_day = 15 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M8';
UPDATE qitp_cabins SET dismantle_day = 14 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M9';
UPDATE qitp_cabins SET dismantle_day = 13 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M10';
UPDATE qitp_cabins SET dismantle_day = 13 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M11';
UPDATE qitp_cabins SET dismantle_day = 12 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M12';
UPDATE qitp_cabins SET dismantle_day = 11 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M13';
UPDATE qitp_cabins SET dismantle_day = 10 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M14';
UPDATE qitp_cabins SET dismantle_day = 9 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M15';
UPDATE qitp_cabins SET dismantle_day = 8 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M16';
UPDATE qitp_cabins SET dismantle_day = 8 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M17';
UPDATE qitp_cabins SET dismantle_day = 7 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M18';
UPDATE qitp_cabins SET dismantle_day = 6 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M19';
UPDATE qitp_cabins SET dismantle_day = 5 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M20';
UPDATE qitp_cabins SET dismantle_day = 4 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M21';
UPDATE qitp_cabins SET dismantle_day = 3 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M22';
UPDATE qitp_cabins SET dismantle_day = 3 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M23';
UPDATE qitp_cabins SET dismantle_day = 2 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M24';
UPDATE qitp_cabins SET dismantle_day = 19 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M25';
UPDATE qitp_cabins SET dismantle_day = 19 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M26';
UPDATE qitp_cabins SET dismantle_day = 19 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M27';
UPDATE qitp_cabins SET dismantle_day = 18 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M28';
UPDATE qitp_cabins SET dismantle_day = 18 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M29';
UPDATE qitp_cabins SET dismantle_day = 17 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M30';
UPDATE qitp_cabins SET dismantle_day = 16 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M31';
UPDATE qitp_cabins SET dismantle_day = 15 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M32';
UPDATE qitp_cabins SET dismantle_day = 14 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M33';
UPDATE qitp_cabins SET dismantle_day = 14 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M34';
UPDATE qitp_cabins SET dismantle_day = 13 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M35';
UPDATE qitp_cabins SET dismantle_day = 12 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M36';
UPDATE qitp_cabins SET dismantle_day = 11 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M37';
UPDATE qitp_cabins SET dismantle_day = 10 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M38';
UPDATE qitp_cabins SET dismantle_day = 9 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M39';
UPDATE qitp_cabins SET dismantle_day = 9 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M40';
UPDATE qitp_cabins SET dismantle_day = 8 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M41';
UPDATE qitp_cabins SET dismantle_day = 7 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M42';
UPDATE qitp_cabins SET dismantle_day = 6 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M43';
UPDATE qitp_cabins SET dismantle_day = 5 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M44';
UPDATE qitp_cabins SET dismantle_day = 5 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M45';
UPDATE qitp_cabins SET dismantle_day = 4 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M46';
UPDATE qitp_cabins SET dismantle_day = 3 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M47';
UPDATE qitp_cabins SET dismantle_day = 2 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'M48';
UPDATE qitp_cabins SET dismantle_day = 17 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T1';
UPDATE qitp_cabins SET dismantle_day = 16 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T2';
UPDATE qitp_cabins SET dismantle_day = 15 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T3';
UPDATE qitp_cabins SET dismantle_day = 15 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T4';
UPDATE qitp_cabins SET dismantle_day = 14 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T5';
UPDATE qitp_cabins SET dismantle_day = 13 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T6';
UPDATE qitp_cabins SET dismantle_day = 12 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T7';
UPDATE qitp_cabins SET dismantle_day = 11 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T8';
UPDATE qitp_cabins SET dismantle_day = 11 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T9';
UPDATE qitp_cabins SET dismantle_day = 10 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T10';
UPDATE qitp_cabins SET dismantle_day = 9 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T11';
UPDATE qitp_cabins SET dismantle_day = 8 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T12';
UPDATE qitp_cabins SET dismantle_day = 7 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T13';
UPDATE qitp_cabins SET dismantle_day = 6 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T14';
UPDATE qitp_cabins SET dismantle_day = 6 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T15';
UPDATE qitp_cabins SET dismantle_day = 5 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T16';
UPDATE qitp_cabins SET dismantle_day = 4 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T17';
UPDATE qitp_cabins SET dismantle_day = 3 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T18';
UPDATE qitp_cabins SET dismantle_day = 2 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T19';
UPDATE qitp_cabins SET dismantle_day = 1 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T20';
UPDATE qitp_cabins SET dismantle_day = 1 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T21';
UPDATE qitp_cabins SET dismantle_day = 1 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T22';
UPDATE qitp_cabins SET dismantle_day = 17 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T23';
UPDATE qitp_cabins SET dismantle_day = 17 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T24';
UPDATE qitp_cabins SET dismantle_day = 16 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T25';
UPDATE qitp_cabins SET dismantle_day = 15 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T26';
UPDATE qitp_cabins SET dismantle_day = 14 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T27';
UPDATE qitp_cabins SET dismantle_day = 13 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T28';
UPDATE qitp_cabins SET dismantle_day = 12 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T29';
UPDATE qitp_cabins SET dismantle_day = 12 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T30';
UPDATE qitp_cabins SET dismantle_day = 11 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T31';
UPDATE qitp_cabins SET dismantle_day = 10 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T32';
UPDATE qitp_cabins SET dismantle_day = 9 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T33';
UPDATE qitp_cabins SET dismantle_day = 8 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T34';
UPDATE qitp_cabins SET dismantle_day = 7 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T35';
UPDATE qitp_cabins SET dismantle_day = 7 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T36';
UPDATE qitp_cabins SET dismantle_day = 6 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T37';
UPDATE qitp_cabins SET dismantle_day = 5 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T38';
UPDATE qitp_cabins SET dismantle_day = 4 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T39';
UPDATE qitp_cabins SET dismantle_day = 3 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T40';
UPDATE qitp_cabins SET dismantle_day = 2 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T41';
UPDATE qitp_cabins SET dismantle_day = 2 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T42';
UPDATE qitp_cabins SET dismantle_day = 1 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T43';
UPDATE qitp_cabins SET dismantle_day = 1 WHERE project_id = (SELECT id FROM projects WHERE code='26004') AND number = 'T44';
